language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - nightly

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

after_success:
  - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Lapidary.jl"); Pkg.clone("https://github.com/BioJulia/Contributing"); cd(Pkg.dir("Contributing")); include(joinpath("docs", "make.jl"))'
