language: julia

os:
  - linux

julia:
  - 0.6

notifications:
  email: false

before_script:
  - export PATH=$HOME/.local/bin:$PATH

after_success:
  - julia -e 'Pkg.clone("https://github.com/BioJulia/Contributing"); cd(joinpath(Pkg.dir("Contributing"), "docs/src")); mkdir("assets"); cd("assets"); run(pipeline(`curl https://codeload.github.com/BioJulia/assets/tar.gz/master`, `tar -xz --strip=2 assets-master/doc_assets`))'
  - julia -e 'cd(Pkg.dir("Contributing")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
