# Project information
site_name: Contributing to BioJulia
site_description: Contribution policy and guidelines for contributors
site_author: The BioJulia Organisation
site_url: https://biojulia.github.io/Contributing/

# Repository
repo_url:  https://github.com/BioJulia/Contributing/
repo_name: 'Github'

# Copyright
copyright: Copyright (c) 2016 The BioJulia Organisation

# Documentation and theme
theme: biojulia
docs_dir: 'build'

# Options
extra:
  author:
    github: BioJulia

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

# Page tree
pages:
  - Home: index.md
  - Contribution Guides (How to...):
      - Contribute fixes:
      - Contribute packages: package_submission.md
      - Join the BioJulia GitHub organisation: join_biojulia.md
  - Policies and Guidelines:
      - Code Style: policy/code_style.md
      - Package Requirements: policy/package_requirements.md
      - Pull Requests: policy/pull_requests.md
      - Off-boarding: policy/off_boarding.md
